### ISSUE TITLE
Error: could not fetch affected tables or last updated time

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/node-cartodb-query-tables#4]
Seen multiple times in Windshaft-cartodb logs:
```
Error: could not fetch affected tables or last updated time: relation "[CENSORED]" does not exist
    at handleAffectedTablesAndLastUpdatedTimeRows (/home/ubuntu/www/node-windshaft/releases/20190320092606/node_modules/cartodb-query-tables/lib/querytables.js:42:29)
    at Result.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190320092606/node_modules/cartodb-psql/lib/psql.js:325:24)
    at Result.Query.handleError (/home/ubuntu/www/node-windshaft/releases/20190320092606/node_modules/pg/lib/query.js:161:17)
    at Client.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190320092606/node_modules/pg/lib/client.js:192:26)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190320092606/node_modules/pg/lib/connection.js:135:12)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
```

As with https://github.com/CartoDB/camshaft/issues/383 this kind of errors leave the tiler in an inconsistent status, which could lead to other issues (or the process dying depending on the node release).

cc/ @CartoDB/rt-managers

**Comment by Algunenano** [comment]
Guessing this was fixed in the 0.6.0 refactor
